name: base

channels:
  - pytorch
  - conda-forge

dependencies:
  - python==3.8.13
  - flask==2.2.2
  - gunicorn>=20.0.4
  - hyperopt==0.2.7
  - matplotlib==3.5.3
  - numpy==1.23.2
  - pandas==1.4.3
  - pandas-flavor>=0.2.0
  - pip==22.1.2
  - pytorch==1.12.1
  - rdkit==2022.03.5
  - scikit-learn==1.1.2
  - scipy==1.9.1
  - tensorboardX>=2.0
  - torchvision==0.13.1
  - tqdm==4.64.1
  - pip:
    - chemprop==1.5.2
    - descriptastorus>=2.3.0.6
    - typed-argument-parser==1.7.2
